name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install and Generate Assets
        run: npm install
      - name: Archive Assets
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: ./dist/
          filename: siitec.zip
      - name: Attach release files.
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./dist/siitec.zip"]'