name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM dependencies
        run: npm install
      - name: Generate Assets
        run: npm run build
      - name: Archive Assets
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: './dist/'
          filename: 'siitec-assets.zip'
      - name: Archive Samples
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: './samples/'
          filename: 'samples.zip'
      - name: Attach release files
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/siitec-assets.zip,./samples/samples.zip"
          token: ${{ secrets.GITHUB_TOKEN }}